<?php

/*
 * Wording used in the PDF sales report. The language is chosen by the
 * mobile application, which sends its current language with the request.
 */

return [
    'title'          => 'Sales Profit Report',
    'generated'      => 'Generated:',
    'period'         => 'Period:',
    'period_all'     => 'All Time',
    'period_start'   => 'Beginning',
    'period_end'     => 'Today',
    'period_to'      => 'to',

    'column_index'   => '#',
    'column_product' => 'Product Name',
    'column_buying'  => 'Buying Price',
    'column_qty'     => 'Qty Sold',
    'column_selling' => 'Selling Price',
    'column_profit'  => 'Profit',

    'no_data'        => 'No data found for the selected date range.',
    'no_summary'     => 'No summary available.',

    'total_items'    => 'Total Items Sold',
    'total_profit'   => 'Total Profit',

    'footer'         => 'Generated by Smart Inventory System',
];
